### ISSUE TITLE
Operating in Chrome on Mac

### ISSUE THREAD

**Issue by John02458** [lurume84/bling-viewer#1]
I tried to open Chrome on Mac as you suggested.  This is a screenshot of the commands:

[ss1.1.pdf](https://github.com/lurume84/bling-viewer/files/3030855/ss1.1.pdf)

The first one included the file name and Chrome did not open.

The second one did not include the file name.  Chrome opened and then I tried opening the file.  The following was the result.  Could not get past Sign-in.
[ss2.2.pdf](https://github.com/lurume84/bling-viewer/files/3030863/ss2.2.pdf)

Thanks for looking into this.

**Comment by John02458** [comment]
Just tried first command again with "/" at end and got error message "Google Chrome can not read/write to its data directory."

**Comment by lurume84** [comment]
Follow instructions described here

https://alfilatov.com/posts/run-chrome-without-cors/

Basically you have to call

open -n -a /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --args --user-data-dir="/tmp/chrome_dev_test" --disable-web-security

When chrome is opened you should see message about web-security. If so, open index.html.

Let's see if this solves the problem!

**Comment by John02458** [comment]
Yes!  That did the trick.  Thanks.

John Morganti
morganti.john@ieee.org

**Comment by lurume84** [comment]
Great! I have just released a version with a better activity viewer FYI

**Comment by John02458** [comment]
How do I download the latest version?  Just download viewer and it will replace the existing as needed? Download only updated folders/files to replace existing?  Or delete existing completely and then download all?

John Morganti
morganti.john@ieee.org

**Comment by lurume84** [comment]
As you cannot use Desktop application, you will need to download new releases every time. If you want to have wip you can directly download the whole source using git so you have one working copy. You then just have to pull changes to that folder. As you have macOS it may directly have git installed.
