### ISSUE TITLE
Linux client - console mode

### ISSUE THREAD

**Issue by vampywiz17** [lurume84/bling-viewer#2]
Hello there,

It would be great, that this great program is avaliable in linux machines, with command line. 

I (and i think not only me) would like to integrate it with home automation system (like Domoticz. Node-Red)

It would be great, that possible to run it on linux server and the app generate a mini website (a specific port) that we able to access it, to view the live stream. 

other question. possible to "listen" the motion detection, without watch the live stream(drain battery)? The IFTTT is really slow...

It would be great to use a service in linux, that listen the motion detections (not only Retrieves per minute, but push it immediately) and we able to send this data to MQTT or any other method.

A guy make a great python based program that do some trick, but you a few steps ahead of him (like live stream): https://github.com/fronzbot/blinkpy/

**Comment by lurume84** [comment]
I'm not a Linux guy I'm sorry. Bling engine is OS-agnostic but uses some third party libraries that are available only for Windows so it's difficult to fully port it to Linux,

If you confirm my app works with Wine in Linux I can expose all Bling internal functionality in a Windows console application.

I do not discard creating a Blink Linux version for other reasons but I'm involved in other projects at this time,

**Comment by konsumer** [comment]
Is there anything in this version that makes it require Windows? I don't see any Windows-specific stuff here (I do in the desktop project.) I'm happy to help with making sure it works in Linux & mac.

I'd also be happy to port the proxy to node, and create a little webserver for it all, so it could be used without cors stuff (just run server.) This might help with getting desktop to work cross-platform, too.

**Comment by konsumer** [comment]
I am actually working on porting the data-part from [this](https://github.com/MattTW/BlinkMonitorProtocol) to node, so if you want to use that, it should be much easier for cross-platform electron & CORS-disabled browser. [Here](https://github.com/konsumer/blink-data) is the start of that, but it still has some work to go.

**Comment by lurume84** [comment]
Great! Actually I am migrating my projets for using cmake/conan so it should be easier to port it to linux/mac. CrashRPT library is for Windows so it has to be changed, the rest is cross-platform. For live view it is needed to have a desktop app so a complete solution cannot be achieved with a webapp. Another user controbuted with a perl script, check it out.

**Comment by konsumer** [comment]
I noticed these 2 endpoints are failing for me. Do they work for you, or do you have another way to get data about thumbs & live-views?

```js
`https://rest-${region}.immedia-semi.com/network/${network}/camera/${camera}/thumbnail`
`https://rest-${region}.immedia-semi.com/api/v3/networks/${network}/cameras/${camera}/liveview`
```

I'm going to keep playing with it, and see if I can figure it out.

**Comment by konsumer** [comment]
I worked it out. [here](https://github.com/konsumer/blink-data/blob/master/src/api.js) is reference until I get more of the endpoints wrapped, but I worked out alternative API calls, and like a million other endpoints.
